/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    get: operations["GetUsers"];
    post: operations["CreateUser"];
  };
  "/users/{id}": {
    get: operations["GetUser"];
    put: operations["UpdateUser"];
    delete: operations["DeleteUser"];
  };
  // ... more paths will be generated here by backend
}

export interface components {
  schemas: {
    UserDto: {
      id: string;
      username: string;
      email: string;
      roles: ("SuperAdmin" | "Admin" | "Editor" | "Support" | "Finance" | "Ops")[];
      isActive: boolean;
      createdAt: string;
    };
    TemplateListItemDto: {
      id: string;
      slug: string;
      name: string;
      templateType: string;
      price: number;
      currency: string;
      status: string;
      createdAt: string;
      media?: { src: string }[];
    };
    TemplateDetailDto: {
      id: string;
      slug: string;
      name: string;
      // ... more fields
    };
    BlogPostDto: {
      id: string;
      title: string;
      slug: string;
      coverImage: string;
      category: string;
      status: "draft" | "published";
      views: number;
      createdAt: string;
    };
    OrderDto: {
      id: string;
      userEmail: string;
      total: number;
      currency: string;
      status: "pending" | "processing" | "completed" | "cancelled" | "refunded";
      paymentStatus: "pending" | "paid" | "failed" | "refunded";
      createdAt: string;
    };
    PaymentDto: {
      id: string;
      orderId: string;
      amount: number;
      currency: string;
      status: "success" | "failed" | "pending";
      provider: string;
      createdAt: string;
    };
    ContactDto: {
      id: string;
      name: string;
      emailOrPhone: string;
      message: string;
      status: "New" | "InProgress" | "Done";
      source?: string;
      createdAt: string;
    };
    SystemLogDto: {
      id: string;
      type: string;
      severity: "info" | "warn" | "error";
      message: string;
      createdAt: string;
    };
    DeployTargetDto: { id: string; name: string };
    SiteDto: { id: string; name: string; domain: string };
    JobDto: { id: string; status: string };
    HealthDto: { service: string; status: "healthy" | "unhealthy"; timestamp: string };
  };
}

export interface operations {
  GetUsers: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"][];
        };
      };
    };
  };
  // ... more operations
}
